### ISSUE TITLE
Mini-cart: layout improvements 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#128]
Reproduce: 
1. Add at least one item to cart 
2. Mouse over cart to trigger flyout 

Issue: The flyout looks quite messy, I'd suggest the following layout improvements: 

1. Display product thumbnail image per line item 
2. Use a font that is much more condensed and that doesn't come in all caps - currently, the product name is larger than the flyout's headline, for instance 
3. Display quantity and style attributes on individual lines, maybe even less prominent than the product name 
4. The subtotal should be right-aligned with the item totals 

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/8910643c-6a0c-4c07-8782-42da12ca6f0a)

**Comment by kqmpetenz** [comment]
When clicking on the mini cart dropdown, the window locks onto the screen. Is that intentional? I suggest to only be able to open the mini cart via hover (same for user menu). Also when you open the mini cart, the window just plops up instantly. I think it would be better if we have some kind of animnation, just like the categories of the top navigation.

**Comment by KFie** [comment]
@kqmpetenz Please see https://github.com/Xceptance/posters-demo-store/issues/124 for the issue you are mentioning.

**Comment by freddyka** [comment]
Issue fixed for poster v2.1.
