### ISSUE TITLE
Search: disable search icon if search field is empty 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#130]
Reproduce: 
1. Do not put anything into search field 
2. Click search icon 

Issue: It is possible to submit an empty search. This can be avoided by deactivating the button if nothing has been provided. 

Uploading 2023-08-04_11h11_05.mp4…

**Comment by rschwietzke** [comment]
Avoid an empty search. Client-side blocking is ok for our purposes as long as the server does not do a find-all query and suffers from that search. If you also want to deal with the server, an empty search should produce a no-results found page.

**Comment by freddyka** [comment]
The issue has been resolved for poster v2.1.

Note:
When searching with empty search field, user gets directed to the homepage with message 
“× Sorry! No results found matching your search. Please try again.”

--> This happens when u try to search on a product detail page or any other page. Maybe don't redirect the user to the homepage and rather to the page they were trying a search from.
