### ISSUE TITLE
Order confirmation page: hide checkout progress indicator 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#171]
Reproduce: 
1. Add random item to cart 
2. Proceed through checkout until you arrive on the order confirmation page 

Issue: The order confirmation page shows the checkout progress indicator. Since the order is completed at this point and the user can't go back to a previous step anymore, I suggest to remove it. 

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/0db1f494-9d9b-4156-9540-e40a509cd99e)

**Comment by kqmpetenz** [comment]
The OrderConfirmationPage is currently the only page where it's possible to do a proper validation of the progress indicator due to plenty of individual selectors. I suggest to insert those selectors for all of the other pages also containing the progress indicator before we get rid of it on the OrderConfirmationPage. That would also ensure the correct execution of my test automation for the progress indicator.

**Comment by rschwietzke** [comment]
Let's keep the checkout indicator and visualize the flow to the end user.
