### ISSUE TITLE
Storefront: Limit pagination button display based on state

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#270]
Don't display "Previous <<" or "Next >>" when there is no such page. For instance on the first or the last page, this should be either gone (preferred) or disabled.

**Comment by EliasTatX** [comment]
Some additional problematic points that relate to this: the current << and >> buttons only jump to the start and end. We might want additional buttons for that purpose if we want this functionality. The buttons also only display "[current page link]/#" on hover instead of a useful prompt. We might want to remove this hover prompt or adjust the content.
