### ISSUE TITLE
Integrity Constraint Violations Fix - Introduction of Duplicate Entries in DB 

### ISSUE THREAD

**Issue by msaroshali** [Xceptance/posters-demo-store#337]
We were facing integrity constraint violation errors when trying to delete customer account, with order creating data still intact inside the account.

**Comment by rschwietzke** [comment]
## Basic Idea for Commerce

* The Order is independent including addresses, line items, payment, and more
* An order is only created when the customer places it, not before, the checkout process does not create an "empty" order when it starts
* The cart is basically an order that has not been placed and it contains the same data and things but it is more actively modified and typically contains addresses, line items and payments as reference and not as copy
* When creating and order, the cart is "converted" into an order which has states such as new, failed, created. The states are part of the final processing, because the payment is done after an order exists and might fail. Or we fail due to inventory not being available (inventory does not yet exist in Posters).
* Anonymous Carts expire when the session is expired (we keep it simple for now)
* Carts are attached to registered on user when the log on or when the cart is created for a session with a logged on user (which replaces the previous cart they might had)

Important: Cart references to addresses and products are not DB references! This would makes maintenance impossible. This are references by text aka ID, so you say, product A with (internal) ID 69ffd249-4750-457d-b904-c205e803f27b is part of the cart but this is not a foreign key relation but the ID is a a "text" and when you display or calculate the cart, you have to check all of this weak references and if needed, drop it as well as read the updated data.
